FROM nginx:1.23.4


RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt update && apt install -y nodejs yarn
RUN npm install n -g
RUN n 18.16.0

COPY . .
COPY custom_nginx.conf /etc/nginx/nginx.conf
RUN yarn build

COPY dist /usr/share/nginx/html
